"""Run with a JSON fixture generated by scripts/verify-python.mjs."""
import importlib.util
import json
import sys
from pathlib import Path

path = Path(__file__).resolve().parents[1] / "snowflake" / "streamlit_app.py"
spec = importlib.util.spec_from_file_location("chainshield_native", path)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
payload = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
module.validate_data(payload["data"])
for index, check in enumerate(payload["checks"]):
    result = module.plan(check["input"], payload["data"])
    for actual, expected in zip(result["candidates"], check["expected"]):
        for field, value in expected.items():
            assert actual[field] == value, (index, check["input"], field, actual[field], value)
print(f"Python planner matched Node planner for {len(payload['checks'])} scenarios and all five strategies.")
