-- Prepared setup; not executed against your account yet.
-- Run with a role permitted to create a database, schema and warehouse.
-- Warehouse usage consumes credits; XS, auto-suspend and initially suspended.
CREATE DATABASE IF NOT EXISTS CHAINSHIELD_DEMO;
CREATE SCHEMA IF NOT EXISTS CHAINSHIELD_DEMO.CORE;
CREATE WAREHOUSE IF NOT EXISTS CHAINSHIELD_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
USE DATABASE CHAINSHIELD_DEMO;
USE SCHEMA CORE;
USE WAREHOUSE CHAINSHIELD_WH;

CREATE TABLE IF NOT EXISTS SUPPLIERS (SUPPLIER_ID VARCHAR PRIMARY KEY, NAME VARCHAR, QUALIFIED BOOLEAN);
CREATE TABLE IF NOT EXISTS PARTS (PART_ID VARCHAR PRIMARY KEY, NAME VARCHAR, BASE_UNIT_COST NUMBER(12,2));
CREATE TABLE IF NOT EXISTS PLANTS (PLANT_ID VARCHAR PRIMARY KEY, NAME VARCHAR);
CREATE TABLE IF NOT EXISTS CUSTOMERS (CUSTOMER_ID VARCHAR PRIMARY KEY, NAME VARCHAR);
CREATE TABLE IF NOT EXISTS ORDERS (
  ORDER_ID VARCHAR PRIMARY KEY, CUSTOMER_ID VARCHAR, PART_ID VARCHAR, PLANT_ID VARCHAR,
  QUANTITY NUMBER(12,0), DUE_DATE DATE, UNIT_VALUE NUMBER(12,2),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
  FOREIGN KEY (PART_ID) REFERENCES PARTS(PART_ID), FOREIGN KEY (PLANT_ID) REFERENCES PLANTS(PLANT_ID)
);
CREATE TABLE IF NOT EXISTS INVENTORY (
  INVENTORY_ID VARCHAR PRIMARY KEY, PLANT_ID VARCHAR, PART_ID VARCHAR,
  QUANTITY NUMBER(12,0), RESERVED_QUANTITY NUMBER(12,0),
  FOREIGN KEY (PART_ID) REFERENCES PARTS(PART_ID), FOREIGN KEY (PLANT_ID) REFERENCES PLANTS(PLANT_ID)
);
CREATE TABLE IF NOT EXISTS SHIPMENTS (
  SHIPMENT_ID VARCHAR PRIMARY KEY, SUPPLIER_ID VARCHAR, PART_ID VARCHAR, PLANT_ID VARCHAR,
  QUANTITY NUMBER(12,0), EXPECTED_ARRIVAL DATE,
  FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
  FOREIGN KEY (PART_ID) REFERENCES PARTS(PART_ID), FOREIGN KEY (PLANT_ID) REFERENCES PLANTS(PLANT_ID)
);
CREATE TABLE IF NOT EXISTS RECOVERY_ROUTES (
  ROUTE_ID VARCHAR PRIMARY KEY, KIND VARCHAR, SUPPLIER_ID VARCHAR,
  FROM_PLANT_ID VARCHAR, TO_PLANT_ID VARCHAR, PART_ID VARCHAR,
  CAPACITY NUMBER(12,0), ARRIVAL_DATE DATE, INCREMENTAL_UNIT_COST NUMBER(12,2), EVIDENCE_ID VARCHAR
);
CREATE TABLE IF NOT EXISTS DOCUMENTS (DOCUMENT_ID VARCHAR PRIMARY KEY, TITLE VARCHAR, BODY VARCHAR);
-- Snowflake standard-table PK/FK constraints are metadata, not uniqueness enforcement.
-- Data validation queries in 04_validate.sql check uniqueness and references explicitly.
