-- Generated from data.mjs. Synthetic fixture; as-of 2026-10-02.
-- Inserts missing IDs only; existing rows are preserved.
USE DATABASE CHAINSHIELD_DEMO;
USE SCHEMA CORE;
USE WAREHOUSE CHAINSHIELD_WH;

INSERT INTO SUPPLIERS (SUPPLIER_ID, NAME, QUALIFIED)
SELECT 'S-PRIMARY', 'Western Precision', TRUE
WHERE NOT EXISTS (SELECT 1 FROM SUPPLIERS WHERE SUPPLIER_ID = 'S-PRIMARY');

INSERT INTO SUPPLIERS (SUPPLIER_ID, NAME, QUALIFIED)
SELECT 'S-ALT', 'Eastern Components', TRUE
WHERE NOT EXISTS (SELECT 1 FROM SUPPLIERS WHERE SUPPLIER_ID = 'S-ALT');

INSERT INTO PARTS (PART_ID, NAME, BASE_UNIT_COST)
SELECT 'P-101', 'Precision valve assembly', 220
WHERE NOT EXISTS (SELECT 1 FROM PARTS WHERE PART_ID = 'P-101');

INSERT INTO PLANTS (PLANT_ID, NAME)
SELECT 'PL-PUNE', 'Pune assembly plant'
WHERE NOT EXISTS (SELECT 1 FROM PLANTS WHERE PLANT_ID = 'PL-PUNE');

INSERT INTO PLANTS (PLANT_ID, NAME)
SELECT 'PL-CHENNAI', 'Chennai reserve depot'
WHERE NOT EXISTS (SELECT 1 FROM PLANTS WHERE PLANT_ID = 'PL-CHENNAI');

INSERT INTO CUSTOMERS (CUSTOMER_ID, NAME)
SELECT 'C-1', 'Aster Motors'
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMERS WHERE CUSTOMER_ID = 'C-1');

INSERT INTO CUSTOMERS (CUSTOMER_ID, NAME)
SELECT 'C-2', 'Meridian Auto'
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMERS WHERE CUSTOMER_ID = 'C-2');

INSERT INTO CUSTOMERS (CUSTOMER_ID, NAME)
SELECT 'C-3', 'Kinetic Mobility'
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMERS WHERE CUSTOMER_ID = 'C-3');

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, PART_ID, PLANT_ID, QUANTITY, DUE_DATE, UNIT_VALUE)
SELECT 'O-1001', 'C-1', 'P-101', 'PL-PUNE', 50, '2026-10-05', 4200
WHERE NOT EXISTS (SELECT 1 FROM ORDERS WHERE ORDER_ID = 'O-1001');

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, PART_ID, PLANT_ID, QUANTITY, DUE_DATE, UNIT_VALUE)
SELECT 'O-1002', 'C-2', 'P-101', 'PL-PUNE', 60, '2026-10-07', 3800
WHERE NOT EXISTS (SELECT 1 FROM ORDERS WHERE ORDER_ID = 'O-1002');

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, PART_ID, PLANT_ID, QUANTITY, DUE_DATE, UNIT_VALUE)
SELECT 'O-1003', 'C-3', 'P-101', 'PL-PUNE', 40, '2026-10-08', 4000
WHERE NOT EXISTS (SELECT 1 FROM ORDERS WHERE ORDER_ID = 'O-1003');

INSERT INTO INVENTORY (INVENTORY_ID, PLANT_ID, PART_ID, QUANTITY, RESERVED_QUANTITY)
SELECT 'INV-PUNE', 'PL-PUNE', 'P-101', 30, 0
WHERE NOT EXISTS (SELECT 1 FROM INVENTORY WHERE INVENTORY_ID = 'INV-PUNE');

INSERT INTO INVENTORY (INVENTORY_ID, PLANT_ID, PART_ID, QUANTITY, RESERVED_QUANTITY)
SELECT 'INV-CHENNAI', 'PL-CHENNAI', 'P-101', 90, 30
WHERE NOT EXISTS (SELECT 1 FROM INVENTORY WHERE INVENTORY_ID = 'INV-CHENNAI');

INSERT INTO SHIPMENTS (SHIPMENT_ID, SUPPLIER_ID, PART_ID, PLANT_ID, QUANTITY, EXPECTED_ARRIVAL)
SELECT 'SH-001', 'S-PRIMARY', 'P-101', 'PL-PUNE', 150, '2026-10-04'
WHERE NOT EXISTS (SELECT 1 FROM SHIPMENTS WHERE SHIPMENT_ID = 'SH-001');

INSERT INTO RECOVERY_ROUTES (ROUTE_ID, KIND, SUPPLIER_ID, FROM_PLANT_ID, TO_PLANT_ID, PART_ID, CAPACITY, ARRIVAL_DATE, INCREMENTAL_UNIT_COST, EVIDENCE_ID)
SELECT 'ALT-01', 'alternate', 'S-ALT', NULL, 'PL-PUNE', 'P-101', 80, '2026-10-06', 180, 'DOC-ALT'
WHERE NOT EXISTS (SELECT 1 FROM RECOVERY_ROUTES WHERE ROUTE_ID = 'ALT-01');

INSERT INTO RECOVERY_ROUTES (ROUTE_ID, KIND, SUPPLIER_ID, FROM_PLANT_ID, TO_PLANT_ID, PART_ID, CAPACITY, ARRIVAL_DATE, INCREMENTAL_UNIT_COST, EVIDENCE_ID)
SELECT 'TR-01', 'transfer', NULL, 'PL-CHENNAI', 'PL-PUNE', 'P-101', 60, '2026-10-04', 120, 'DOC-DEPOT'
WHERE NOT EXISTS (SELECT 1 FROM RECOVERY_ROUTES WHERE ROUTE_ID = 'TR-01');

INSERT INTO RECOVERY_ROUTES (ROUTE_ID, KIND, SUPPLIER_ID, FROM_PLANT_ID, TO_PLANT_ID, PART_ID, CAPACITY, ARRIVAL_DATE, INCREMENTAL_UNIT_COST, EVIDENCE_ID)
SELECT 'EXP-01', 'expedite', 'S-PRIMARY', NULL, 'PL-PUNE', 'P-101', 150, '2026-10-04', 60, 'DOC-EXP'
WHERE NOT EXISTS (SELECT 1 FROM RECOVERY_ROUTES WHERE ROUTE_ID = 'EXP-01');

INSERT INTO DOCUMENTS (DOCUMENT_ID, TITLE, BODY)
SELECT 'DOC-PRIMARY', 'Primary supplier dispatch notice', 'SH-001 has 150 units of P-101 for Pune. Baseline delivery is day 2. Delay is entered by the scenario operator; it is a simulated assumption.'
WHERE NOT EXISTS (SELECT 1 FROM DOCUMENTS WHERE DOCUMENT_ID = 'DOC-PRIMARY');

INSERT INTO DOCUMENTS (DOCUMENT_ID, TITLE, BODY)
SELECT 'DOC-ALT', 'Alternate supplier qualification and offer', 'Eastern Components is qualified for P-101. Up to 80 additional units arrive on day 4. Incremental cost is INR 180 per unit including freight. The scenario can revoke qualification or reduce available capacity.'
WHERE NOT EXISTS (SELECT 1 FROM DOCUMENTS WHERE DOCUMENT_ID = 'DOC-ALT');

INSERT INTO DOCUMENTS (DOCUMENT_ID, TITLE, BODY)
SELECT 'DOC-DEPOT', 'Chennai stock reservation policy', 'Chennai holds 90 units; 30 are reserved for local obligations and cannot be transferred. The remaining 60 can reach Pune on day 2 at INR 120 per unit.'
WHERE NOT EXISTS (SELECT 1 FROM DOCUMENTS WHERE DOCUMENT_ID = 'DOC-DEPOT');

INSERT INTO DOCUMENTS (DOCUMENT_ID, TITLE, BODY)
SELECT 'DOC-EXP', 'Expedited transport offer', 'Expediting can recover up to four days of transport delay, with arrival no earlier than day 2. Incremental cost is INR 60 per unit. Regular and expedited transport share the same SH-001 shipment quantity; they are not separate stock.'
WHERE NOT EXISTS (SELECT 1 FROM DOCUMENTS WHERE DOCUMENT_ID = 'DOC-EXP');

INSERT INTO DOCUMENTS (DOCUMENT_ID, TITLE, BODY)
SELECT 'DOC-METRICS', 'Planning assumptions and business definitions', 'One finished unit consumes one P-101 component. Partial fulfilment is allowed. Objective: maximize on-time units, then minimize incremental recovery cost. At-risk value equals uncovered units times order unit value; it is exposure, not booked revenue loss. Production time is assumed included in route arrival days. This fixture excludes multi-part bills of materials, uncertain transit, and full-order-only constraints.'
WHERE NOT EXISTS (SELECT 1 FROM DOCUMENTS WHERE DOCUMENT_ID = 'DOC-METRICS');

