USE DATABASE CHAINSHIELD_DEMO;
USE SCHEMA CORE;
USE WAREHOUSE CHAINSHIELD_WH;
-- Expected: 150 units, 598000 INR; total order value, not scenario exposure.
SELECT SUM(QUANTITY) AS TOTAL_UNITS, SUM(QUANTITY * UNIT_VALUE) AS TOTAL_ORDER_VALUE FROM ORDERS;
-- Expected: 30 units Pune, 60 Chennai transferable.
SELECT PLANT_ID, QUANTITY - RESERVED_QUANTITY AS AVAILABLE FROM INVENTORY;
-- Expected: no rows in all anomaly checks.
SELECT ORDER_ID, COUNT(*) FROM ORDERS GROUP BY ORDER_ID HAVING COUNT(*) > 1;
SELECT SHIPMENT_ID, COUNT(*) FROM SHIPMENTS GROUP BY SHIPMENT_ID HAVING COUNT(*) > 1;
SELECT SUPPLIER_ID, COUNT(*) FROM SUPPLIERS GROUP BY SUPPLIER_ID HAVING COUNT(*) > 1;
SELECT PART_ID, COUNT(*) FROM PARTS GROUP BY PART_ID HAVING COUNT(*) > 1;
SELECT PLANT_ID, COUNT(*) FROM PLANTS GROUP BY PLANT_ID HAVING COUNT(*) > 1;
SELECT CUSTOMER_ID, COUNT(*) FROM CUSTOMERS GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1;
SELECT INVENTORY_ID, COUNT(*) FROM INVENTORY GROUP BY INVENTORY_ID HAVING COUNT(*) > 1;
SELECT ROUTE_ID, COUNT(*) FROM RECOVERY_ROUTES GROUP BY ROUTE_ID HAVING COUNT(*) > 1;
SELECT DOCUMENT_ID, COUNT(*) FROM DOCUMENTS GROUP BY DOCUMENT_ID HAVING COUNT(*) > 1;
SELECT * FROM INVENTORY WHERE RESERVED_QUANTITY > QUANTITY OR RESERVED_QUANTITY < 0 OR QUANTITY < 0;
SELECT o.ORDER_ID FROM ORDERS o
  LEFT JOIN CUSTOMERS c ON c.CUSTOMER_ID = o.CUSTOMER_ID
  LEFT JOIN PARTS p ON p.PART_ID = o.PART_ID
  LEFT JOIN PLANTS pl ON pl.PLANT_ID = o.PLANT_ID
  WHERE c.CUSTOMER_ID IS NULL OR p.PART_ID IS NULL OR pl.PLANT_ID IS NULL;
SHOW SEMANTIC VIEWS IN SCHEMA CHAINSHIELD_DEMO.CORE;
SHOW SEMANTIC METRICS IN CHAINSHIELD_DEMO.CORE.ORDER_COMMITMENTS;
SHOW SEMANTIC METRICS IN CHAINSHIELD_DEMO.CORE.INBOUND_SUPPLY;
