-- Optional: run after setup with a role able to create/grant roles.
-- This role can read the fixture but cannot modify it. It is not an admin role.
CREATE ROLE IF NOT EXISTS CHAINSHIELD_READER;
GRANT USAGE ON WAREHOUSE CHAINSHIELD_WH TO ROLE CHAINSHIELD_READER;
GRANT USAGE ON DATABASE CHAINSHIELD_DEMO TO ROLE CHAINSHIELD_READER;
GRANT USAGE ON SCHEMA CHAINSHIELD_DEMO.CORE TO ROLE CHAINSHIELD_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA CHAINSHIELD_DEMO.CORE TO ROLE CHAINSHIELD_READER;
GRANT SELECT ON SEMANTIC VIEW CHAINSHIELD_DEMO.CORE.ORDER_COMMITMENTS TO ROLE CHAINSHIELD_READER;
GRANT SELECT ON SEMANTIC VIEW CHAINSHIELD_DEMO.CORE.INBOUND_SUPPLY TO ROLE CHAINSHIELD_READER;
-- Grant CHAINSHIELD_READER to your user using the exact username in your account.
